json.partial! partial: "pools/pool_details", locals: { pool: @pool }

json.trade_state @pool.trade_policy_result
json.games_active @pool.league.games_active?

json.pool_teams do
  json.array! @pool.pool_teams do |team|
    json.id team.id
    json.team_name team.team_name
    json.rank @team_ranks[team.id]
    json.total_score @team_scores[team.id] || 0.0

    json.user do
      json.id team.owner.id
      json.name team.owner.name
    end
  end
end
