@scorings_by_stat_type.each_key do |stat_type|
  json.set! stat_type do
    json.array! @scorings_by_stat_type[stat_type] do |scoring|
      json.id scoring[:id]
      json.stat_type scoring[:stat_type]
      json.field_name scoring[:field_name]
      json.descriptive @stat_config::STAT_LABELS[scoring[:field_name].to_sym] || scoring[:field_name].titleize
      json.value scoring[:value]
    end
  end
end
