json.using_reference_season @pool.using_reference_season?
json.trading_state @pool.trade_policy_result
json.pending_trades @has_pending_trades

json.boxes do
  json.array! @boxes do |box|
    json.id box.id
    json.name box.name
    json.order box.position

    json.players do
      json.array! box.players do |player|
        json.id player.id
        json.name player.name
        json.current_team_short_code player.current_team_short_code

        json.selected @selected_ids.include?(player.id)

        scores = @player_scores[player.id]

        json.partial! partial: "players/scores", locals: { scores: scores[:scores], clipped: nil }
      end
    end
  end
end
