import {
  Trophy,
  Handshake,
  Target,
  Shield,
  BrickWall,
  Medal,
  Clock,
  Zap,
  Gavel,
  Swords,
  Star,
  CheckLine,
  BadgeCheck,
  CircleMinus,
  CheckCheck,
  Diff,
  Crosshair,
  CircleCheck,
  RefreshCw,
} from "lucide-react";

export const PWHL_STAT_ICON_MAP = {
  goals: Trophy,
  assists: Handshake,
  shots: Crosshair,
  hits: Swords,
  saves: Shield,
  shutout: BrickWall,
  win: Medal,
  penalty_minutes: Clock,
  power_play_goals: Zap,
  short_handed_goals: Gavel,
  faceoffs_won: Star,
  shots_blocked: CheckLine,
  game_winning_goals: BadgeCheck,
  goals_against: CircleMinus,
  plus_minus: Diff,
  shots_against: Target,
  game_started: CircleCheck,
  faceoffs_taken: RefreshCw,
};
