json.id @player.id
json.name @player.name
json.current_team_id @player.current_team_id
json.current_team_short_code @player.current_team.short_code

json.raw_stats do
  json.partial! partial: 'players/scores', locals: { scores: @stats[:stats], clipped: @stats[:clipped_stats] }
end

json.pool_scores do
  json.partial! partial: 'players/scores', locals: { scores: @scores[:stats], clipped: @scores[:clipped_stats] }
end

json.labels do
  json.goals "Goals"
  json.assists "Assists"
  json.shots "Shots"
  json.hits "Hits"
  json.saves "Saves"
  json.shutout "Shutout"
  json.win "Win"
  json.penalty_minutes "PIM"
  json.power_play_goals "PPG"
  json.short_handed_goals "SHG"
  json.faceoffs_won "Faceoffs Won"
  json.faceoffs_taken "Faceoffs"
  json.time_on_ice "TOI"
  json.plus_minus "+/-"
  json.shots_against "SA"
  json.goals_against "GA"
  json.game_started "GP"
  json.game_winning_goals "GWG"
  json.shots_blocked "Blocked"
end
