json.scores do
  json.today scores[:today]
  json.yesterday scores[:yesterday]
  json.week_to_date scores[:week_to_date]
  json.month_to_date scores[:month_to_date]
  json.season_to_date scores[:season_to_date]
end

json.clipped_scores do
  json.today clipped[:today]
  json.yesterday clipped[:yesterday]
  json.week_to_date clipped[:week_to_date]
  json.month_to_date clipped[:month_to_date]
  json.season_to_date clipped[:season_to_date]
end
