json.boxes do
  json.array! @result do |(box_name, entry)|
    json.name box_name
    json.position entry[:position]

    json.players do
      json.array! entry[:players] do |player|
        json.partial! partial: "commissioner/pool_boxes/box_player", locals: { player: player }
      end
    end
  end
end

json.free_agents do
  json.array! @free_agents do |player|
    json.partial! partial: "commissioner/pool_boxes/box_player", locals: { player: player }
  end
end
