json.boxes do
  json.array! @result.keys do |box_name|
    players = @result[box_name]
    json.name box_name

    json.players do
      json.array! players do |player|
        json.partial! partial: "commissioner/pool_boxes/box_player", locals: { player: player }
      end
    end
  end
end

json.free_agents do
  json.array! @free_agents do |player|
    json.partial! partial: "commissioner/pool_boxes/box_player", locals: { player: player }
  end
end
